apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  frontend.conf: |
    upstream backend {
        server backend;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }