apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits-request-test" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "100m" 
        memory: "6Mi" 
    - type: "Container"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "100m" 
        memory: "4Mi" 
      default:
        cpu: "300m" 
        memory: "1Gi" 
      defaultRequest:
        cpu: "100m" 
        memory: "500Mi" 
