apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod-x
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: gcr.io/google_containers/serve_hostname
    resources:
      limits:
        cpu: "100m"
        memory: "400Mi"
      requests:
        cpu: "100m"
        memory: "400Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod-y
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: gcr.io/google_containers/serve_hostname
    resources:
      limits:
        cpu: "100m"
        memory: "400Mi"
      requests:
        cpu: "100m"
        memory: "400Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod-z
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: gcr.io/google_containers/serve_hostname
    resources:
      limits:
        cpu: "100m"
        memory: "400Mi"
      requests:
        cpu: "100m"
        memory: "400Mi"
